### ISSUE TITLE
Can not optimize ASM JSON file

### ISSUE THREAD

**Issue by gsscoder** [costa-group/gasol-optimizer#32]
I've created the file using `solc `compiler command version 0.8.17:

```shell
$ solc --combined-json asm ./contracts/OutwaveEvent.sol --base-path . --include-path ./node_modules 1> ./asmjsonfiles/OutwaveEvent.asmjson
```

But when I try to optimize it I get the following error:

```shell
$ python3 ~/src/gasol-optimizer/gasol_asm.py ./asmjsonf
iles/OutwaveEvent.asmjson
Traceback (most recent call last):
  File "/home/coder/src/gasol-optimizer/gasol_asm.py", line 721, in <module>
    optimize_asm_in_asm_format(args.input_path, output_file, csv_file, log_file, args.tout, args.log_flag, args.storage,
  File "/home/coder/src/gasol-optimizer/gasol_asm.py", line 559, in optimize_asm_in_asm_format
    asm = parse_asm(file_name)
  File "/home/coder/src/gasol-optimizer/sfs_generator/parser_asm.py", line 120, in parse_asm
    asm_c = build_asm_contract(c,contracts[c]["asm"])
  File "/home/coder/src/gasol-optimizer/sfs_generator/parser_asm.py", line 72, in build_asm_contract
    raise Exception("ERROR. Check")
Exception: ERROR. Check
```

Best regards

**Comment by alexcere** [comment]
Hi @gsscoder,

Main branch works for solc versions up to 0.8.13, as version 0.8.14 modified the structure of the assembly file. Issue #23 addresses this change and contains the code for avoiding the exception. Nevertheless, I recommend using the branch `smt_refactor` instead of the main one. This branch is still under development, but it can work with contracts compiled in version 0.8.17 and also corrects some bugs we have detected. There are still some parts that are under construction, but the main functionalities should work alright. Hopefully, we will make a release soon, as we are running extensive experiments to guarantee everything is alright. If you need any help, don't hesitate to contact us :)

**Comment by gsscoder** [comment]
@alexcere Thanks for explanation, details and for sharing the tool

For the moment we decided to rely on other means to audit gas metrics

Have a nice day :)
